### ISSUE TITLE
UCE writeback sequence should wait for the write response

### ISSUE THREAD

**Issue by farzamgl** [black-parrot/black-parrot#475]
Currently, during a writeback, UCE sends a read commands followed by a write command to writeback the dirty data. But after sending these commands it only waits for the read response before jumping back to the ready state. This could cause the late write response from the cache to happen at the same time as the response for the next instruction and break the top-level arbiter between cache and other devices.

**Comment by dpetrisko** [comment]
We shouldn't wait on writebacks (performance hit) but we should fix the response arbitration.

The sequence here is:
- WB read
- WB write
- IO read

- WB read response
- WB write response / IO read response

We should write a basic test for this, also

**Comment by farzamgl** [comment]
What's the point of the wb write response? Where is it used?

**Comment by dpetrisko** [comment]
credit counting for fences

**Comment by taylor-bsg** [comment]
Seems like a warning sign about this module that there is some concurrency
that has not been thought through?

**Comment by dpetrisko** [comment]
Yeah, the problem is that responses from different destinations can return unexpectedly. The arbitration was written as one-hot because it was assumed there was only 1 outstanding request from each cache, but this does not hold when CLINT or I/O is involved

**Comment by taylor-bsg** [comment]
Sounds like in the comments there should be some explicit reasoning about
what concurrent events can happen. Arbiters dropping things under rare
concurrent events is common bug pattern that takes a long time to track
down due to the infrequency of such events.  Generally the assumption for
any module should be that if it has multiple interfaces, they are
concurrent; and when possible non-concurrent interfaces should be collapsed
into a single interface (particularly if the non-concurrent interface comes
from the same place).

Will update the style guide with this...

**Comment by dpetrisko** [comment]
The bug isn't in the UCE.  The bug is in the arbitration here:
https://github.com/black-parrot/black-parrot/blob/master/bp_top/src/v/bp_softcore.v#L428

Note the (incorrect) comment that says the responses are guaranteed to be one-hot

**Comment by taylor-bsg** [comment]
Oh I see. Perhaps we should have a BSG_ASSERT_ONE_HOT(clk,signal) and a
BSG_ASSERT_ONE_HOT_OR_ZERO(clk,signal) in BaseJump STL to check one
hotness? There are some SVA primitives, but presumably we want to have
module-wide control over them for tool independence.

M
