### ISSUE TITLE
Remove internal message header buffering in CCE's (lce_req, lce_resp, mem_resp)

### ISSUE THREAD

**Issue by muwyse** [black-parrot/black-parrot#869]
- [ ] Remove LCE Request header buffer
- [ ] Remove LCE Response header buffer
- [x] Remove Memory Response header buffer (or determine if unable to)

**Comment by muwyse** [comment]
Memory Response requires buffering to avoid deadlock in the coherence protocol. The CCE needs space for two messages on this channel since it may issue two memory commands prior to resolving the speculative issue of a cache block fetch.

**Comment by dpetrisko** [comment]
Where should we document this?

**Comment by muwyse** [comment]
I think best places are:
- https://github.com/black-parrot/black-parrot/blob/me_dev/docs/bedrock_coherence_protocol.md
- coherence deep dive doc (added by ME interface PR)
- comments in the code, at the stream pumps (I did add brief comments here, although they could be reworded to more explicitly state that the buffer size must be two elements)

**Comment by dpetrisko** [comment]
Yeah the first one can maybe mention in that Priority section about how LCE cmd depends on mem cmd / mem resp being completed. 

I haven’t looked through the second one. 

The third, do you mean commenting at the CCE instantiation of stream pumps? I think that’s the correct place for saying exactly the sizing of the buffers since it’s implementation specific (you could theoretically have a different buffering strategy etc)

**Comment by dpetrisko** [comment]
This is done
